import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import UiKitHeader from '../components/UiKitHeader'
import LotteryEntrance from '../components/LotteryEntrance'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rinkeby Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* manual header  <Header /> */}
      <UiKitHeader />
      <LotteryEntrance />
    </div>
  )
}
